development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017
  options:

test:
  sessions:
    default:
      database: test
      hosts:
        - localhost

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        consistency: strong
        max_retries: 1
        retry_interval: 0
        skip_version_check: true
        safe: true